apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx
    #type: NodePort
  type: LoadBalancer
