- hosts: localhost
  vars:
    namespace: "demo"
  gather_facts: no
  connection: local
  tasks:
    - name: Create Namespace {{ namespace }}
      command: "kubectl create namespace {{ namespace }}"
    - name: Deploy nodejsapp
      command: "helm upgrade --install nodejsapp nodejsapp --namespace {{ namespace }}"
