apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deploy
  labels:
    app: app1
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: {{ .Values.app1.image }}:{{ .Values.version }}
        ports:
        - containerPort: 3000
