apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deploy
  labels:
    app: app2
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: {{ .Values.app2.image }}:{{ .Values.version }}
        ports:
        - containerPort: 3001
