apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.frontend.image }}:{{ .Values.version }}
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nodejs-conf
              mountPath: "/etc/nginx/conf.d/"
      volumes:
       - name: nodejs-conf
         configMap:
          name: nodejs-conf
